### ISSUE TITLE
mongoimport

### ISSUE THREAD

**Issue by vizo** [arozwalak/my-todo-app#1]
With command:
mongoimport -d mytodoapp -c users data/todos.json
i get error:
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of

I had to use:
mongoimport -d mytodoapp --jsonArray  -c users data/todos.json

**Comment by arozwalak** [comment]
On what system did you have this error? I imported this file on windows and osx without problems, but it's good to know the solution for that case, thanks.

**Comment by vizo** [comment]
Ubuntu 15.10

**Comment by arozwalak** [comment]
thanks, I'll update README.md
